version: 3

env:
  NOT_CRAN: true

tasks:
  test:
    cmds:
      - Rscript -e "devtools::test()"
  install:
    deps:
      - document
    cmds:
      - Rscript -e "devtools::install()"
  document:
    cmds:
      - Rscript -e "rextendr::document()"
