# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_lamp_wrappers", use_symbols = TRUE, package_name = "lamp")

#' @usage NULL
#' @useDynLib lamp, .registration = TRUE
NULL

as_tensor_numeric <- function(array, device) .Call(wrap__as_tensor_numeric, array, device)

int_new_cuda <- function(ordinal) .Call(wrap__int_new_cuda, ordinal)

as_tensor_matrix <- function(matrix, device) .Call(wrap__as_tensor_matrix, matrix, device)

as_tensor_matrix_3d <- function(matrix, device) .Call(wrap__as_tensor_matrix_3d, matrix, device)

print_tensor <- function(tensor) invisible(.Call(wrap__print_tensor, tensor))

add_tensor <- function(lhs, rhs) .Call(wrap__add_tensor, lhs, rhs)

mul_tensor <- function(lhs, rhs) .Call(wrap__mul_tensor, lhs, rhs)

div_tensor <- function(lhs, rhs) .Call(wrap__div_tensor, lhs, rhs)

sub_tensor <- function(lhs, rhs) .Call(wrap__sub_tensor, lhs, rhs)

int_new_tensor <- function(array, dims, device) .Call(wrap__int_new_tensor, array, dims, device)

int_collect_tensor <- function(tensor) .Call(wrap__int_collect_tensor, tensor)

dot_tensor <- function(lhs, rhs) .Call(wrap__dot_tensor, lhs, rhs)

get_device <- function(tensor) .Call(wrap__get_device, tensor)


# nolint end
